[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 0
y = 0

[font.normal]
family = "HackGen Console NF"

[font.bold]
family = "HackGen Console NF"

[font.italic]
family = "HackGen Console NF"

[font.bold_italic]
family = "HackGen Console NF"

[font]
size = 15.0

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 1
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#011627"
bright_foreground = "#eeeeee"
foreground = "#bdc1c6"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"
