Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AsciiComments:
  Enabled: false

classAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'
