require: rubocop-rails

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/**/*.rb
    - db/migrate/*.rb
    - lib/tasks/**/*.rake
    - Gemfile

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  Max: 120
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
