[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
build = ':UpdateRemotePlugins'
depends = ['neosnippet.vim']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function() abort
    return deoplete#close_popup() . "\<CR>"
  endfunction
'''

hook_post_source = '''
  call deoplete#custom#source('LanguageClient',
              \ 'min_pattarn_length',
              \ 2)
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
build = ':GoUpdateBinaries'
