[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'Tags',
  'Buffers',
  'Rg!',
]
hook_add = '''
  nnoremap <silent> <leader>; :<C-u>Buffers<CR>
  nnoremap <silent> <leader>f :<C-u>Files<CR>
  nnoremap <silent> <leader>t :<C-u>Tags<CR>
  nnoremap <silent> <leader>g :<C-u>Rg!<CR>
  command! -bang -nargs=* Rg
   \ call fzf#vim#grep(
   \   'rg --column --line-number --no-heading --color=auto --smart-case '.shellescape(<q-args>), 1,
   \   <bang>0 ? fzf#vim#with_preview('up:60%')
   \           : fzf#vim#with_preview('right:50%:hidden', '?'),
   \   <bang>0)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
hook_add = '''
  let NERDTreeShowHidden=1
  nnoremap <silent> <leader>e :<C-u>NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['ruby']
hook_add = '''
  let b:ale_fixers = {
    \ 'ruby': ['rubocop'],
    \ }
  let g:ale_sign_column_always = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
'''
