[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'Tags',
  'Buffers',
  'Rg!',
]
hook_add = '''
  nnoremap <silent> <leader>; :<C-u>Buffers<CR>
  nnoremap <silent> <leader>f :<C-u>Files<CR>
  nnoremap <silent> <leader>t :<C-u>Tags<CR>
  nnoremap <silent> <leader>g :<C-u>Rg!<CR>
  nnoremap <silent> <C-]> :call fzf#vim#tags(expand('<cword>'))<CR>
  command! -bang -nargs=* Rg
   \ call fzf#vim#grep(
   \   'rg --column --line-number --no-heading --color=auto --smart-case '.shellescape(<q-args>), 1,
   \   <bang>0 ? fzf#vim#with_preview('up:60%')
   \           : fzf#vim#with_preview('right:50%:hidden', '?'),
   \   <bang>0)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
hook_add = '''
  let NERDTreeShowHidden=1
  nnoremap <silent> <leader>e :<C-u>NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'eruby']

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['ruby', 'python']
hook_add = '''
  nnoremap <silent> <leader>l :<C-u>ALEToggle<CR>
  nnoremap <silent> <leader>a :<C-u>ALEFix<CR>
  let g:ale_linters = {
    \ 'ruby': ['rubocop'],
    \ 'python': ['flake8'],
    \ }
  let g:ale_fixers = {
    \ 'ruby': ['rubocop'],
    \ 'python': ['autopep8', 'black'],
    \ }
  let g:ale_sign_column_always = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_enter = 1
  let g:ale_python_flake8_executable = g:python3_host_prog
  let g:ale_python_flake8_options = '-m flake8'
  let g:ale_python_autopep8_executable = g:python3_host_prog
  let g:ale_python_autopep8_options = '-m autopep8'
  let g:ale_python_black_executable = g:python3_host_prog
  let g:ale_python_black_options = '-m black'
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']
