[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'Tags',
  'Buffers',
  'Rg!',
]
hook_add = '''
  nnoremap <silent> <Space>b :<C-u>Buffers<CR>
  nnoremap <silent> <Space>f :<C-u>Files<CR>
  nnoremap <silent> <Space>t :<C-u>Tags<CR>
  nnoremap <silent> <Space>g :<C-u>Rg!<CR>
  command! -bang -nargs=* Rg
   \ call fzf#vim#grep(
   \   'rg --column --line-number --no-heading --color=auto --smart-case '.shellescape(<q-args>), 1,
   \   <bang>0 ? fzf#vim#with_preview('up:60%')
   \           : fzf#vim#with_preview('right:50%:hidden', '?'),
   \   <bang>0)
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
