[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nnoremap <silent> <leader>y :<C-u>TagbarToggle<CR>
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <Leader>gs :<C-u>Gstatus<CR>
  nnoremap <silent> <Leader>gd :<C-u>Gdiff<CR>
  nnoremap <silent> <Leader>gb :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
  nmap s <Nop>
  xmap s <Nop>
'''

# [[plugins]]
# repo = 'jacoborus/tender.vim'
# hook_add = '''
#   if (has("termguicolors"))
#      set termguicolors
#   endif
#   syntax enable
#   colorscheme tender
# '''
# 
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# depends = ['tender.vim']
# hook_add = '''
#   let g:lightline={
#     \ 'colorscheme': 'tender',
#     \ 'active': {
#     \   'left': [ ['mode', 'paste'],
#     \             ['readonly', 'filepath', 'modified'] ]
#     \ },
#     \ 'component_function': {
#     \   'filepath': 'FilePath',
#     \ },
#     \ }
# 
#   function! FilePath()
#     if winwidth(0) > 90
#       return expand('%')
#     else
#       return expand('%:t')
#     end
#   endfunction
# '''

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'
# hook_add = '''
#   set hidden
#   let g:LanguageClient_serverCommands = {
#       \ 'ruby': ['solargraph', 'stdio'],
#       \ }
# 
#   nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
#   nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
#   nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  if (has("termguicolors"))
     set termguicolors
     let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
     let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  endif
  syntax enable
  colorscheme iceberg
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = '''
  let g:lightline={
    \ 'colorscheme': 'iceberg',
    \ 'active': {
    \   'left': [ ['mode', 'paste'],
    \             ['readonly', 'filepath', 'modified'] ]
    \ },
    \ 'component_function': {
    \   'filepath': 'FilePath',
    \ },
    \ }

  function! FilePath()
    if winwidth(0) > 90
      return expand('%')
    else
      return expand('%:t')
    end
  endfunction
'''
